-- MySQL Script generated by MySQL Workbench
-- Rab 07 Jul 2021 07:12:38 
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema bahasa_pemrograman
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bahasa_pemrograman`;
-- -----------------------------------------------------
-- Schema bahasa_pemrograman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bahasa_pemrograman`;
USE `bahasa_pemrograman`;
-- -----------------------------------------------------
-- Table `bahasa_pemrograman`.`daftar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bahasa_pemrograman`.`daftar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(255) NULL,
  `deskripsi` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
-- -----------------------------------------------------
-- Data for table `bahasa_pemrograman`.`daftar`
-- -----------------------------------------------------
START TRANSACTION;
USE `bahasa_pemrograman`;
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (1, 'C', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (2, 'C#', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (3, 'C++', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (4, 'Go', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (5, 'Java', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (6, 'Kotlin', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (7, 'Pascal', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (8, 'Perl', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (9, 'PHP', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (10, 'Python', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (11, 'R', 'Lorem ipsum dolor sit amet.');
INSERT INTO `bahasa_pemrograman`.`daftar` (`id`, `nama`, `deskripsi`)
VALUES (12, 'Ruby', 'Lorem ipsum dolor sit amet.');
COMMIT;